services:
  backend:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/app
      - ./data:/app/data
    command: sh -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 80 "

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    depends_on:
      - backend
