"""change  Purchase to amount

Revision ID: a019ca6f9c0d
Revises: 13667a2c9802
Create Date: 2026-07-03 16:49:27.030461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a019ca6f9c0d'
down_revision: Union[str, Sequence[str], None] = '13667a2c9802'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('expense', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('expense', 'Purchase')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('Purchase', sa.FLOAT(), nullable=False))
    op.drop_column('expense', 'updated_at')
    op.drop_column('expense', 'amount')
    # ### end Alembic commands ###
